default: &default
  adapter: postgresql
  encoding: unicode
  username: c00p75
  password: 1234
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  port: 5433

development:
  <<: *default
  database: rails_back_end_developmentent
  
test:
  <<: *default
  database: rails_back_end_test

production:
  <<: *default
  database: rails_back_end_production
  username: rails_back_end
  password: <%= ENV["HELLO_RAILS_BACK_END_DATABASE_PASSWORD"] %>
